---
- hosts: all
  sudo: yes
  remote_user: root
  pre_tasks:
    - name: 'update apt'
      raw: sudo apt-get update
    - name: 'install python'
      raw: sudo apt-get -y install python-simplejson
  gather_facts: no
